#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    autoSelect,     sensorPotentiometer)
#pragma config(Sensor, dgtl1,  skyriseClaw,    sensorDigitalOut)
#pragma config(Sensor, dgtl2,  cubeIntake,     sensorDigitalOut)
#pragma config(Sensor, dgtl3,  ,               sensorDigitalOut)
#pragma config(Sensor, dgtl4,  rightShaft,     sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  leftShaft,      sensorQuadEncoder)
#pragma config(Sensor, I2C_1,  backLeftEnc,    sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  backRightEnc,   sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_4,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_5,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_6,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           botLeft,       tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           midLeft,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           midRight,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           topLeft,       tmotorVex393_MC29, openLoop, encoderPort, I2C_5)
#pragma config(Motor,  port5,           topRight,      tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_6)
#pragma config(Motor,  port6,           backLeft,      tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port7,           frontLeft,     tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_2)
#pragma config(Motor,  port8,           frontRight,    tmotorVex393_MC29, openLoop, encoderPort, I2C_3)
#pragma config(Motor,  port9,           backRight,     tmotorVex393_MC29, openLoop, encoderPort, I2C_4)
#pragma config(Motor,  port10,          botRight,      tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "states.h"
#include "arm.h"
#include "intakeControl.h"
#include "drive.h"
#include "userControl.h"
#include "autonTasks.h"
#include "autonSwitcher.h"

task main(){
	//startTask(lcd);												//1000 does 90 degree turn on regular tiled floor

	//cubeAuto(RED);
	//
}
